syntax = "proto3";

option csharp_namespace = "GameProto";

// ── Heartbeat (PacketType 0x0011 / 0x0012) ───────────────────────────────────

message Ping {}
message Pong {}

// ── Move (PacketType 0x0101 / 0x0102) ────────────────────────────────────────

message MoveRequest {
  float x = 1;
  float y = 2;
  float z = 3;
}

message MoveResponse {
  int32 player_id = 1;
  float x         = 2;
  float y         = 3;
  float z         = 4;
}

// ── Chat (PacketType 0x0201 / 0x0202) ────────────────────────────────────────

message ChatRequest {
  string message = 1;
}

message ChatBroadcast {
  int32  player_id = 1;
  string username  = 2;
  string message   = 3;
}


// ── PlayerEnter/Leave ────────────────────────────────────────


message PlayerEnter {
  int32  player_id = 1;
  string username  = 2;
  float  x         = 3;
  float  y         = 4;
}

message PlayerLeave {
  int32 player_id = 1;
}

message ZoneSnapshot {
  repeated PlayerEnter players = 1;
}

message RequestZoneSnapshot {
}

message ZoneTransferRequest { int32 target_zone_id = 1; }

message ZoneTransferResponse {
    bool success = 1;
    int32 zone_id = 2;
    float spawn_x = 3;
    float spawn_y = 4;
}

// ── Skill ────────────────────────────────────────

message SkillRequest {}

message SkillResponse {
  int32 player_id = 1; int32 color_index = 2; int32 atk = 3; 
}

// ── Combat ────────────────────────────────────────

message DamageResponse { 
  int32 attacker_id = 1; int32 target_id = 2; int32 damage = 3; int32 remain_hp = 4; 
}

message DeathResponse  { 
 int32 dead_player_id = 1; 
}

message RespawnResponse {
  int32 player_id = 1; float x = 2; float y = 3; int32 hp = 4; 
}
